name: Automatic Run

on:
  push:
    branches: [ main ]


jobs:
  Compile:
    runs-on: ubuntu-latest
    name: Compilando Java + maven
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      - name: Step 3 - Build Maven
        run: mvn compile

  Test:
    runs-on: ubuntu-latest
    name: Ejecutando tests
    needs: Compile
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      - name: Step 3 - Download Latest Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: Step 4 - Install Google Chrome
        run: sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Step 5 - Run Tests
        run: mvn test -Pheadless

      - name: Step 6 - Generar Reportes (Artifact)
        uses: actions/upload-artifact@v2
        with:
          name: Reporte-Autoc0de-Web-Chrome
          path: target/Reports/
